import { Routes } from '@angular/router';
import { Home } from './pages/home/home';
import { Login } from './pages/login/login';
import { Register } from './pages/register/register';
import { RegisterMedecin } from './pages/register-medecin/register-medecin';
import { RegisterPatient } from './pages/register-patient/register-patient';
import { ForgotPasswordComponent } from './pages/forgot-password/forgot-password';
import { AdminDashboard } from './pages/admin/admin-dashboard/admin-dashboard';
import { MedecinsList } from './pages/admin/medecins-list/medecins-list';
import { AddMedecin } from './pages/admin/add-medecin/add-medecin';
import { PatientsList } from './pages/admin/patients-list/patients-list';
import { AddPatient } from './pages/admin/add-patient/add-patient';
import { SpecialitesList } from './pages/admin/specialites-list/specialites-list';
import { AddSpecialite } from './pages/admin/add-specialite/add-specialite';
import { ServicesList } from './pages/admin/services-list/services-list';
import { AddService } from './pages/admin/add-service/add-service';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'login', component: Login },
  { path: 'register', component: Register },
  { path: 'register/medecin', component: RegisterMedecin },
  { path: 'register/patient', component: RegisterPatient },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'admin-dashboard', component: AdminDashboard },
  { path: 'admin/medecins', component: MedecinsList },
  { path: 'admin/add-medecin', component: AddMedecin },
  { path: 'admin/patients', component: PatientsList },
  { path: 'admin/add-patient', component: AddPatient },
  { path: 'admin/specialites', component: SpecialitesList },
  { path: 'admin/add-specialite', component: AddSpecialite },
  { path: 'admin/services', component: ServicesList },
  { path: 'admin/add-service', component: AddService },
  { path: '**', redirectTo: 'login' }
];